"""Structured Pydantic schemas for LLM reasoning and report outputs."""

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class PolicyStance(str, Enum):
    """Categorical monetary policy stance."""
    ULTRA_HAWKISH = "Ultra-Hawkish"
    HAWKISH = "Hawkish"
    NEUTRAL = "Neutral"
    DOVISH = "Dovish"
    ULTRA_DOVISH = "Ultra-Dovish"


class RegimeClassification(str, Enum):
    """Investment Clock quadrants."""
    GOLDILOCKS = "Goldilocks"
    REFLATION = "Reflation"
    STAGFLATION = "Stagflation"
    DISINFLATION = "Disinflation"
    LATE_CYCLE = "Late-Cycle Transition"


class DialecticalArgument(BaseModel):
    """One side of the Hawk/Dove debate."""
    stance: str = Field(..., description="Hawkish or Dovish stance.")
    key_evidence: List[str] = Field(..., description="Specific data points cited.")
    conclusion: str = Field(..., description="The argument's conclusion.")


class HawkishDovishTone(BaseModel):
    """Quantitative and qualitative tone assessment of a central bank statement."""
    score: float = Field(
        ...,
        ge=-1.0,
        le=1.0,
        description="Continuous score from -1.0 (Extreme Dovish/Easing) to +1.0 (Extreme Hawkish/Tightening). 0.0 is Neutral.",
    )
    stance: PolicyStance = Field(..., description="Categorical stance classification.")
    confidence: float = Field(
        ..., ge=0.0, le=1.0, description="Confidence level of the LLM assessment."
    )
    key_phrases_hawkish: List[str] = Field(
        default_factory=list, description="Direct quotes or phrases indicating tightening or inflation vigilance."
    )
    key_phrases_dovish: List[str] = Field(
        default_factory=list, description="Direct quotes or phrases indicating rate cuts or economic weakness concern."
    )
    rationale: str = Field(..., description="Concise justification of the assigned tone score.")


class MacroAnomalyFlag(BaseModel):
    """Flag for detected macroeconomic anomaly or risk signal."""
    indicator: str = Field(..., description="Name or code of the indicator (e.g., T10Y2Y, CPIAUCSL).")
    severity: str = Field(..., description="Severity level: LOW, MEDIUM, HIGH, CRITICAL.")
    title: str = Field(..., description="Short headline of the anomaly.")
    description: str = Field(..., description="Detailed description of what the data implies.")
    data_source: str = Field(default="FRED", description="Which API the anomaly came from.")
    historical_precedent: Optional[str] = Field(
        None, description="Relevant historical comparison (e.g., 2007 yield curve inversion)."
    )


class MonetaryPolicyShift(BaseModel):
    """Semantic delta detection between current and prior central bank communications."""
    institution: str = Field(..., description="Name of the institution (e.g., Fed FOMC, ECB).")
    previous_tone_score: Optional[float] = None
    current_tone_score: float
    tone_delta: float = Field(..., description="Change in score (current - previous).")
    semantic_pivot_summary: str = Field(..., description="Summary of key vocabulary changes.")


class MacroPulseReportData(BaseModel):
    """Complete structured synthesis generated by the MacroSentinel engine."""
    report_id: str
    generated_at: str
    executive_summary: str = Field(
        ..., description="2-3 paragraph executive summary of the macroeconomic backdrop."
    )
    primary_regime: str = Field(
        ..., description="Current regime: e.g., 'Late-Cycle Disinflation', 'Stagflationary Pressure', 'Goldilocks Soft Landing', 'Recessionary Contraction'."
    )
    tone_assessment: HawkishDovishTone
    regime_classification: Optional[RegimeClassification] = None
    dialectical_debate: Optional[List[DialecticalArgument]] = None
    tone_delta_from_previous: Optional[float] = None
    anomalies: List[MacroAnomalyFlag] = Field(default_factory=list)
    cross_asset_implications: List[str] = Field(
        default_factory=list,
        description="Expected impact on Equities, Fixed Income/Bonds, FX (USD/EUR), and Commodities.",
    )
    actionable_watchpoints: List[str] = Field(
        default_factory=list,
        description="Key upcoming data releases or events to monitor in the next 1-4 weeks.",
    )
